name: Publish Laravel Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: Deploy via SFTP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Adjust to match the PHP version used by your Laravel project
        tools: composer

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Deploy to server via SFTP
      uses: appleboy/ftp-action@v1.1.0
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        local-dir: ./ # The local directory to upload
        remote-dir: ${{ secrets.SFTP_SERVER_PATH }} # The server directory to upload to
