name: Publish Laravel Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy via SFTP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Deploy to server via SFTP
      uses: appleboy/sftp-action@v1.2.0
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22 # Default port for SFTP
        local-dir: ./ # Local directory to upload
        remote-dir: ${{ secrets.SERVER_PATH }} # Remote directory to upload to

    - name: Set correct permissions
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER }} 'chmod -R 755 ${{ secrets.SERVER_PATH }}/storage ${{ secrets.SFTP_SERVER_PATH }}/bootstrap/cache'
